name: No submodule update checker

on:
  pull_request:
    paths:
      - 'RobustToolbox'

jobs:
  this_aint_right:
    name: Submodule update in pr found
    runs-on: WL_runner_x64_Ubuntu
    steps:
      - name: Fail
        run: exit 1
